"""empty message.

Revision ID: 6adcc79486bb
Revises: 2b7380507a71
Create Date: 2025-04-28 16:21:32.572222

"""

import sqlalchemy as sa
from alembic import op
import pgvector
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = "6adcc79486bb"
down_revision = "2b7380507a71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("CREATE EXTENSION IF NOT EXISTS vector;"))

    op.create_table(
        "document_index",
        sa.Column("langchain_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=896),
            nullable=False,
        ),
        sa.Column("langchain_metadata", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("langchain_id"),
    )
    op.alter_column(
        "dummy_model",
        "name",
        existing_type=sa.VARCHAR(length=200),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dummy_model",
        "name",
        existing_type=sa.VARCHAR(length=200),
        nullable=True,
    )
    op.drop_table("document_index")
    # ### end Alembic commands ###
